version: '3'
services:

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb:ypan
    volumes:
      - db:/var/lib/mysql
    restart: always
    networks:
      - inception
    environment:
      MARIADB_ROOT_PASSWORD:  ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE:       ${MARIADB_DATABASE}
      MARIADB_USER:           ${MARIADB_USER}
      MARIADB_PASSWORD:       ${MARIADB_PASSWORD}
  
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress:ypan
    volumes:
      - html:/var/www/html
    depends_on:
      - mariadb
    restart: always
    networks:
      - inception
    environment:
      WORDPRESS_DB_HOST:          ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME:          ${MARIADB_DATABASE}
      WORDPRESS_DB_USER:          ${MARIADB_USER}
      WORDPRESS_DB_PASSWORD:      ${MARIADB_PASSWORD}
      WORDPRESS_DOMAIN_NAME:      ${WORDPRESS_DOMAIN_NAME}
      WORDPRESS_ADMIN_USER:       ${WORDPRESS_ADMIN_USER}
      WORDPRESS_ADMIN_PASSWORD:   ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL:      ${WORDPRESS_ADMIN_EMAIL}
      WORDPRESS_NORMAL_USER:      ${WORDPRESS_NORMAL_USER}
      WORDPRESS_NORMAL_PASSWORD:  ${WORDPRESS_NORMAL_PASSWORD}
      WORDPRESS_NORMAL_EMAIL:     ${WORDPRESS_NORMAL_EMAIL}

  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    image: nginx:ypan
    ports:
      - 443:443
    volumes:
      - html:/var/www/html
    depends_on:
      - wordpress
    restart: always
    networks:
      - inception

volumes:
  db:
    driver: local
    driver_opts:
      type: volume
      o: bind
      device: /home/ypan/data/db
  html:
    driver: local
    driver_opts:
      type: volume
      o: bind
      device: /home/ypan/data/html

networks:
  inception:

